language: node_js
node_js:
- node
sudo: required
dist: trusty

branches:
  only:
  - blog
before_install:
# for html-minifier
- sudo pip install Pygments
install:
- mkdir work
- wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  -O $PWD/work/hugo.deb
- sudo dpkg -i $PWD/work/hugo.deb
- npm install
script:
- grunt deploy

env:
  global:
  - REPO="github.com/imet/imet.github.io.git"
  - USER="imet"
  - EMAIL=${email}
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="master"
  - GH_TOKEN=${GH_TOKEN}
